version: "3"

services:

  db:
    restart: always
    image: postgres
    container_name: betoch-postgres
    environment:
      - POSTGRES_USER=betoch-user
      - POSTGRES_PASSWORD=betoch-password
      - POSTGRES_DB=betoch-db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - betoch_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: betoch-pgadmin
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@betoch.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment:
        - POSTGRES_USER=betoch-user
        - POSTGRES_PASSWORD=betoch-password
        - POSTGRES_DB=betoch-db
      ports:
        - "8000:8000"
      depends_on:
        - db
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app/frontend/
      user: node


volumes:
  betoch_data: