# Generated by Django 4.2.1 on 2023-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('has_branch', models.BooleanField()),
                ('has_penality', models.BooleanField()),
                ('penality_percent', models.FloatField()),
            ],
        ),
    ]
