# Generated by Django 4.2.1 on 2023-07-03 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_Name', models.CharField(max_length=100)),
                ('company_Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('has_branch', models.BooleanField(default=False)),
                ('has_penalty', models.BooleanField(default=False)),
                ('penalty_percent', models.FloatField(blank=True, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
