# Generated by Django 4.2.1 on 2023-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='has_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='has_penality',
            field=models.BooleanField(default=False),
        ),
    ]
