# Generated by Django 4.2.1 on 2023-06-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_logo_company_companylogo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyLogo',
            new_name='company_Logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyName',
            new_name='company_Name',
        ),
    ]
