# Generated by Django 4.2.1 on 2023-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_companylogo_company_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='penality_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
