# Generated by Django 4.2.1 on 2023-07-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(blank=True, max_length=50, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('rental_price', models.FloatField(blank=True, null=True)),
                ('Total_Paid', models.FloatField(blank=True, null=True)),
                ('contract_Evidence', models.ImageField(blank=True, null=True, upload_to='')),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('house_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='house.house', verbose_name='house_id')),
            ],
        ),
    ]
