# Generated by Django 4.2.1 on 2023-07-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.CharField(blank=True, null=True)),
                ('rent_Price', models.CharField()),
                ('payment_Term', models.DurationField(blank=True, null=True)),
                ('contract_evidence', models.ImageField(blank=True, null=True, upload_to='')),
                ('has_room', models.BooleanField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branch.branch', verbose_name='branchid')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='companyid')),
            ],
        ),
    ]
