# Generated by Django 4.2.1 on 2023-06-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('company', '0005_rename_companylogo_company_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_Numebr', models.CharField(blank=True, null=True)),
                ('rent_Price', models.CharField()),
                ('peyment_Term', models.DurationField(blank=True, null=True)),
                ('contrat_Evidenc', models.ImageField(blank=True, null=True, upload_to='')),
                ('has_room', models.BooleanField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branch.branch', verbose_name='branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='company')),
            ],
        ),
    ]
