export const NO_AUTHENTICATION = 'NO_AUTHENTICATION';
export const KIRAY_ADMIN_ROLE = 'KIRAY_ADMIN_DASHBOARD';
export const OWNERS_ADMIN_ROLE = 'OWNERS_ADMIN_DASHBOARD';
export const SELLERS_ROLE = 'SELLERS_DASHBOARD';
