# Generated by Django 4.2.1 on 2023-06-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('house', '0002_house_registered_date_house_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_penality_date', models.FloatField(blank=True, null=True)),
                ('penality_amount', models.FloatField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('houseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='house.house', verbose_name='houseid')),
                ('roomid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='room.room', verbose_name='roomid')),
            ],
        ),
    ]
