# Generated by Django 4.2.1 on 2023-06-20 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_company_registered_date_company_status_and_more'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='companyid'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='userid'),
        ),
    ]
