# Generated by Django 4.2.1 on 2023-06-08 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_email_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Kiray_admin'), (2, 'Company_owner_or_admin'), (3, 'Sells')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('801772e8-d6a3-4ee7-bd2a-8e0ea2647cab'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
