# Generated by Django 4.2.1 on 2023-06-14 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'KIRAY_ADMIN'), (2, 'OWNER_OR_ADMIN'), (3, 'SELLS')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8155d71e-9bf4-4a02-bd24-56f387a20668'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
