# Generated by Django 4.2.1 on 2023-06-15 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_role_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('cb3d8cbe-dc77-4b02-afa7-7dd0c63205b4'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
