# Generated by Django 4.2.1 on 2023-06-15 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('40a2d182-acdd-4453-8be8-1b3b52bc2d63'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
