# Generated by Django 4.2.1 on 2023-06-15 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('17d42015-3d82-4c29-86ba-5877f62ccf26'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
