# Generated by Django 4.2.1 on 2023-06-19 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('725cf38d-6330-4cb3-bb27-f44791771e62'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
