# Generated by Django 4.2.1 on 2023-06-19 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e685e583-4c36-43c8-8101-fca97f426292'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
