# Generated by Django 4.2.1 on 2023-06-20 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('21cbf9ae-55d9-44ab-9094-42eff5291df6'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
