# Generated by Django 4.2.1 on 2023-06-20 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('58e0ed3c-d310-4149-bb5a-11651e75b3f2'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
